source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'
inhibit_all_warnings!

xcodeproj 'shuoyeahProject.xcodeproj'

target :shuoyeahProject do
    pod "AFNetworking"
    pod "MBProgressHUD"
    pod “SVProgressHUD”
    pod “MJRefresh”
    pod “SDWebImage”
    pod “IQKeyboardManager”
    pod “MJExtension”
    pod “SDWebImage”
    pod “SDWebImage”
    pod 'MMDrawerController'
end